@URL = http://localhost:5000

### Register
POST {{URL}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Firamir",
  "lastName": "Vau",
  "gender": "male",
  "email": "firarmirr@mail.ru",
  "password": "fuuck_w123"
}

### Login
POST {{URL}}/api/auth/login
Content-Type: application/json

{
  "email": "firarmirr@mail.ru",
  "password": "fuuck_qw123_blyad"
}