@URL = http://localhost:5000

### Register
POST {{URL}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Tesr",
  "lastName": "Tesrov",
  "gender": "male",
  "email": "teet@mail.ru",
  "password": "123456789"
}

### Login
POST {{URL}}/api/auth/login
Content-Type: application/json

{
  "email": "teet@mail.ru",
  "password": "123456789"
}

###
POST {{URL}}/api/reviews
Content-Type: application/json 
{
  "Id": 1,
}
###
GET {{URL}}/api/reviews
Content-Type: application/json 

###
GET {{URL}}/api/articles
Content-Type: application/json 
###
GET {{URL}}/api/users
Content-Type: application/json 

###
POST {{URL}}/api/users/reviews

Content-Type: application/json
{
  "Id": 1,
  "ReviewerId": 2,
  "ArticleId": 1,
  "Status": "sdasd",
  "Rating": 5,
}