@URL = http://localhost:5136

### Register
POST {{URL}}/api/auth/register
Content-Type: application/json

{
  "firstName": "Vladislav",
  "lastName": "Koptsev",
  "gender": "male",
  "email": "firamir@mail.ru",
  "password": "qw123"
}

### Login
POST {{URL}}/api/auth/login
Content-Type: application/json

{
  "email": "firamir@mail.ru",
  "password": "qw123"
}